README.rst
ecs_deploy/cli.py
ecs_deploy/ecs.py
setup.py
tests/test_cli.py
tests/test_ecs.py

This PR adds support for ECS' new task role capabilities and boto's `--task-role-arn` option.
It introduces a new CLI parameter `-r` or `--role` to set a task role ARN on demand.

Task role support

---

ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_cli.py
tests/test_ecs.py

The `task` parameter can be:
- a full task ARN or
- a task family name with a specific revision (e.g. `my-task:123`) or
- just a task family name (e.g. `my-task`). In that case, the most recent revision is used
Fixes #17

Add parameter --task to deploy based on a specific task definition

---

ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_cli.py
tests/test_ecs.py

* only print changed environment variables
* print one line output per changed environment variable
* new flags: `--diff` (default) and `--no-diff` to show/hide the differences of the old and new task definition
Fixes #26

Only print changed environment variables

---

ecs_deploy/ecs.py
setup.py
tests/test_ecs.py

Support new task definition properties like `networkMode` or `placementConstraints`. 
Even though they can not be manipulated with `ecs-deploy` yet, at least these properties retain in the new task definition.
Fixes #25

Support unknown task definition properties

---

ecs_deploy/__init__.py
ecs_deploy/ecs.py
tests/test_ecs.py

The task definition property `requiresAttributes` is not always included in the ECS task definition response. This is currently not used in `ecs-deploy`, so it may be optional.
fixes #35

Make requiresAttributes an optional ECS task definition property

---

ecs_deploy/ecs.py
tests/test_ecs.py

to support services with scheduling strategy `DAEMON`.
Fixes #59

Do not set desiredCount in deploy action, only in scale action a

---

ecs_deploy/ecs.py
tests/test_ecs.py

We're hoping to use ecs-deploy as part of a utility that switches role, determines the service ARN using boto3 and then uses ecs-deploy to update the task definition.
To do this we would be programmatically assuming a role (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-api.html) and need to supply the aws_session_token.

Support for aws_session_token in EcsClient constructor

---

README.rst
ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_cli.py
tests/test_ecs.py

Adds a command line option `-s/--secret` to specify secrets for a task.
AWS recently added the ability to specify secrets in the AWS Parameter
Store which can be injected into the container as environment variables.
See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

Add support for `secrets` in TaskDefinition

---

README.rst
ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_cli.py
tests/test_ecs.py

Add new flags `--exclusive-env` and `--exclusive-secrets` (both default: False) to remove all non-given, but pre-existing environment variables or secrets from the new task definition.
Fixes #74

Set exclusive environment

---

.dockerignore
Dockerfile

I created a Dockerfile, which uses the source code to build an image to run ecs-deploy without any local installation. This way its possible to run a stable release or the development version of ecs-deploy via Docker.
Fixes #85

Create Dockerfile and dockerignore configuration

---

ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_cli.py
tests/test_ecs.py

This pull request adds the `executionRoleArn` by using
* `-x`
* `--execution-role`
The cli option names need to be further discussed, I think.
This pull request resulted from issue #87

Added support to set executionRoleArn on ecs deploy.

---

README.rst
ecs_deploy/ecs.py
tests/test_ecs.py

The --command switch now can take more complicated arguments like this:
```
ecs deploy my-cluster my-service --command my-container '["sh", "-c", "while true; do echo Time files like an arrow $(date); sleep 1; done;"]'
```
`README` and tests are updated.
Please take a look @fabfuel

command switch can now take more complicated arguments.

---

ecs_deploy/ecs.py

When updating a cron job, it loses any network configuration data from the rule as it's overwriting the target. Updating it instead of replacing it ensures any new data is not lost.

allow extra EcsParameters to not be lost when updating rule

---

ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_ecs.py

When running a task with `ecs run`, support choosing between different versions of the Fargate platform.
This allows (as of the time of writing) use of 1.4.0, which is necessary to access EFS from fargate containers.
See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html for more information about platform versions. Confusingly `LATEST` _isn't_ the latest platform version, it is more akin to latest stable.

Support platform version for FARGATE tasks.

---

README.rst

the update command doesn't require a cluster parameter, this reflects that in the README.md

fix readme documentation of the update command

---

README.rst

Fix #188 
Includes docs and doc links for:
* Using `AmazonECS_FullAccess`
* The minimal set of permissions required  to use ecs-deploy (in theory, at least)
* Docs links for setting up `iam:PassRole` correctly

Add IAM permissions docs to README

---

ecs_deploy/cli.py

After finishing a deployment, print the duration (in seconds) on the screen

Print deployment duration

---

setup.py

This PR relaxes the version constraint of the `click` dependency so that versions above `8.0` can be installed. We had to update the version of `celery` that our app was using (previously `5.0.5`) because of a critical security alert. We upgraded to `celery 5.2.2` which requires `click >=8.0,<9.0` but because `ecs-deploy` had locked `click` to `7.1.2`, we could not do this.

Relax click version constraint

---

README.rst
ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_ecs.py

Currently cpu and memory can only be set per-container. This makes it possible to set it at the task level.

new feature: cpu and memory configurable at task level

---

README.rst
ecs_deploy/cli.py
ecs_deploy/ecs.py
tests/test_ecs.py

This PR adds a new option, `--secrets-env-file`, which works in essentially the same way as `--env-file` but adds the key/value pairs from this file into the secrets in the task definition instead of the environment.
The goal here is to allow users to use files like the below:
```
ENV_SECRET=arn:aws:ssm:eu-west-1:1234567890:parameter/app/secret
```
which will result in secrets being added to the task definition in the format:
```
{ name: "ENV_SECRET",  valueFrom: "arn:aws:ssm:eu-west-1:1234567890:parameter/app/secret" }
```
This means, alongside a `.env` file, a single deploy can contain all the secrets and environment variables needed to configure an application correctly.

Add --secrets-env-file option

---

.github/workflows/build.yml

- python 2.7 is not supported anymore in `actions/setup-python`
- dropping it from ci matrix which currently fails with `2.7`
references:
- pip: https://pip.pypa.io/en/latest/development/release-process/#python-2-support
- actions/setup-python: https://github.com/actions/setup-python/issues/672

drop python 2.7 from ci matrix

---

README.rst

- https://github.com/Homebrew/homebrew-core/pull/175212
cc @fabfuel

docs: add homebrew installation note
